website/__init__.py
from flask import Flask
from config import Config

def create_app():
    app = Flask(__name__, static_url_path='/static')
    # key for cookie auth
    # app.config['SECRET KEY'] = 'asdf'
    app.config.from_object(Config)
    from .views import views
    app.register_blueprint(views, url_prefix='/')
    return app

website/views.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from urllib.error import *
import requests
from bs4 import BeautifulSoup
import smtplib


views = Blueprint('views', __name__)

@views.route('/favicon.ico')
def favicon():
    return url_for('static', filename='pictures/favicon.ico')

@views.route('/', methods=['GET', 'POST'])
def home():
    return render_template("index.html")

@views.route('/contact/<info>', methods=['GET', 'POST'])
def contact(info):
    # if request.method == 'POST':
    #     name =  request.form["name"]
    #     email = request.form["email"]
    #     subject = request.form["subject"]
    #     message = request.form["message"]
    #     send_email(name, email, subject, message)
    
    # if request.method == 'GET':
    if info == '0':
        return render_template("contact.html")
    else:
        return render_template("contactsent.html")

@views.route('/form', methods=['POST'])
def form():
    name =  request.form["name"]
    email = request.form["email"]
    subject = request.form["subject"]
    message = request.form["message"]
    send_email(name, email, subject, message) 
    return redirect("/contact/1")

@views.route('/service', methods=['GET', 'POST'])
def service():
    return render_template("service.html")

@views.route('/shop', methods=['GET', 'POST'])
def shop():
    return render_template("shop.html")

@views.route('/bike', methods=['GET', 'POST'])
def bikes():
    result_list = getBikes()
    return render_template("bikes.html", result = result_list)

@views.route('/bikesPB', methods=['GET', 'POST'])
def bikesPB():
    result_list = getBikes()
    return render_template("bikesPB.html", result = result_list)

def send_email(name, email, subject, message):
    email_message = f"Subject:{subject}\n\nName: {name}\nEmail: {email}\nSubject: {subject}\nMessage:\n{message}"
    with smtplib.SMTP("smtp.gmail.com") as connection:
        # connection.starttls()
        # connection.login('chrismitch774@gmail.com', 'xinxvonhqmkhdmrk')
        # connection.sendmail('chrismitch774@gmail.com', 'chrismitch774@gmail.com', email_message)
        connection.starttls()
        connection.login('northshorebikeshop@gmail.com', 'ekicbgetmbnlwbam')
        connection.sendmail('northshorebikeshop@gmail.com', 'northshorebikeshop@gmail.com', email_message)



class Result:
    src = ""
    desc = ""
    mat = ""
    wheelsize = ""
    size = ""
    front_travel = ""
    rear_travel = ""
    price = ""
    bike_page = ""

    def __init__(self, src, desc, mat, wheelsize, size, front_travel, rear_travel, price, bike_page):
        self.src = src
        self.desc = desc
        self.mat = mat
        self.wheelsize = wheelsize
        self.size = size
        self.front_travel = front_travel
        self.rear_travel = rear_travel
        self.price = price
        self.bike_page = bike_page
    

    def make_result(src, desc, mat, wheelsize, size, front_travel, rear_travel, price, bike_page):
        result = Result(src, desc, mat, wheelsize, size, front_travel, rear_travel, price, bike_page)
        return result

def getBikes(): 
    result_list = []
    page = requests.get("https://www.pinkbike.com/u/north-shore-bike-shop/buysell/")
    soup = BeautifulSoup(page.content, "html.parser")
    results = soup.find_all("div", {"class": "bsitem"})
    for i, result in enumerate(results):
        # if (i == 0):
            # print(result)
            table = result.find_all("tr", {"class": "bsitem-table"})[0]
            src = table.find_all("a")[0].find_all("img")[0]["src"]
            
            # print(alink)
            item_details = result.find_all("div", {"class": "bsitem-title"})[0]
            bike_type = item_details.find_all("br")[0].next_sibling.strip()
            if (bike_type == "Enduro Bikes" or bike_type == "Trail Bikes" or bike_type == "Downhill Bikes" or bike_type == "Dirt Jump Bikes"):
                title = item_details.find_all("a")[0]
                website = title['href']
                desc = title.getText()
                more_details = item_details.find_all("div", {"class": "itemdetail"})
                frame_size = more_details[1].getText()
                wheel_size = more_details[2].getText()
                
                if (bike_type == "Dirt Jump Bikes"):
                    front_travel = ""
                    rear_travel = ""
                    material = ""
                else:
                    front_travel = more_details[4].getText()
                    rear_travel = more_details[5].getText()
                    material = more_details[3].getText()
                price = result.find_all('td', {"class": "bsitem-price"})[0].getText()
                # newPage = requests.get(website)
                # newSoup = BeautifulSoup(newPage.content, "html.parser")
                # images = newSoup.find_all('div', {"id": "buysell-image"})
                # if len(images) == 1:
                    # src = images[0]['data-fullimageurl']
                result = Result(src, desc, material, wheel_size, frame_size, front_travel, rear_travel, price, website)
                result_list.append(result)
        
        
        
        

    return result_list
            
        

            
            
    

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>North Shore Bike Shop</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="/static/style.css" />
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700,900|Ubuntu:400,500,700"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="https://use.typekit.net/nbr0zma.css" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <script
      src="https://kit.fontawesome.com/e3cf0159fe.js"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg sticky-top navbar-collapse">
      <div class="container text">
        <a class="navbar-brand" href="{{url_for('views.home')}}">
          <img
            src="/static/pictures/pics/logo.png"
            alt=""
            width="120"
            height="100%"
            class="d-inline-block align-text-top"
          />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navmenu"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navmenu">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a href="{{url_for('views.home')}}" class="nav-link">About</a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Shop
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="{{url_for('views.bikes')}}"
                    >Bikes</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{{url_for('views.shop')}}"
                    >Parts & Gear</a
                  >
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a href="{{url_for('views.service')}}" class="nav-link"
                >Service</a
              >
            </li>
            <li class="nav-item">
              <a href="{{url_for('views.contact', info='0')}}" class="nav-link"
                >Contact</a
              >
            </li>
          </ul>
          <ul class="navbar-nav sm-icons">
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.contact', info='0')}}"
                ><i class="fa-solid fa-location-dot"></i
              ></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div>{% block content %} {% endblock %}</div>
    <section class="section5">
      <div class="row align-items-center justify-content-between">
        <div class="col-md text-center">
          North Shore Bike Shop <br />
          1831 Lonsdale Avenue <br />
          North Vancouver, BC <br />
          V7M 2J8
        </div>
        <div class="col-md p-5 text-center">
          (604)929-6727 (call)<br />
          (604)928-6727 (text)<br />
          northshorebikeshop@gmail.com
        </div>
        <div class="col-md align-items-center text-center">
          <a
            href="https://www.instagram.com/north_shore_bike_shop/"
            target="_blank"
            style="color: #ffffff"
            >Instagram</a
          ><br /><a
            href="https://www.pinkbike.com/u/north-shore-bike-shop/buysell/"
            target="_blank"
            style="color: #ffffff"
            >Pinkbike</a
          >
        </div>
      </div>
    </section>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/bikes.html
{% extends "base.html" %} {% block title %}Changed{% endblock %} {% block
content %}
<div class="container text-center">
  <br />
  <div style="font-family: open-sans, sans-serif; font-size: 40px">
    It's time for your new bike!
  </div>
  <div class="bike-text">
    We are always well-stocked with youth bikes, dirt jumpers, trail, enduro and
    downhill bikes. With a passionate crew of cyclists on staff, we have
    tremendous experience across all disciplines of cycling and are happy to
    help you get the most out of your riding time. Check out our
    <a href="#bikes" style="color: #000"
      >list of in-stock bikes here</a
    >
    to see some of our current options.<br />
    <br />
    We are proud to be dealers of Transition and Norco, two local brands who
    continue to push the boundaries and make the best bikes in the industry.
    Whether you are looking for an entry-level hardtail or the best bike money
    can buy, you will have options at NSBS.
  </div>
  <br />
  <a href="https://www.transitionbikes.com/Home.cfm" target="_blank"
    ><img
      src="/static/pictures/pics/tranny.png"
      class="img-fluid"
      style="width: 60%"
  /></a>
  <div class="bike-text">
    We are proud to be one of the largest Transition Bikes dealers in Canada!
    Transition is a local company from just south of the border, in Bellingham,
    WA. They make high end mountain bikes for all types of riding from XC to DH.
    We are always well stocked in everything Transition offers. Take a look
    <a href="#bikes" style="color: #000">here</a> to see
    some of out in stock transitions.
  </div>

  <a href="https://www.transitionbikes.com/Home.cfm" target="_blank">
    <img
      src="/static/pictures/pics/norco.png"
      class="img-fluid"
      style="width: 60%"
    />
  </a>

  <div class="bike-text">
    Norco is a local brand from Coquitlam, BC that have a broad range of bikes.
    We have Norco mountain bikes for all riders, from beginners looking to do
    some trails and city riding, to experts wanting the fastest and most
    advanced bike you can buy. Take a look
    <a href="#bikes" style="color: #000">here</a> to see
    some of our in stock norcos. We also have many other norcos in stock that
    are not present there, so let us know what you are after and we will let you
    know if we have it / can get it.
  </div>
  <div class="bike-line"></div>
  <a class="anchor" id="bikes"></a>

  <div class="bikeinfo">
    Below is a list of some in-stock bikes we have. We do a fairly good job of
    updating, but it is not always accurate of our stock. We have many more
    bikes in stock than just these. If you are interested in any of these bikes,
    or other options you don't see here, contact us.
  </div>
  {% for r in result %}
  <div class="bike-line"></div>
  <div class="bike">
    <div class="row align-items-center">
      <div class="col-6">
        <a href="{{ r.src }}" target="_blank">
          <img
            src="{{ r.src }}"
            alt=""
            class="img-fluid"
            style="border-radius: 5%"
          />
        </a>
      </div>
      <div class="col-6">
        <a href="{{ r.bike_page }}" target="_blank" style="color: #000000"
          ><div class="title">{{ r.desc }}</div></a
        >
        <div class="title">{{ r.price }}</div>
        {{ r.size }} <br />
        {{ r.wheelsize }}<br />
        {{ r.mat }} <br />
        {{ r.front_travel }} <br />
        {{ r.rear_travel }} <br />
        <a
          href="{{url_for('views.contact', info='0', _anchor='bottom')}}"
          target="_blank"
          style="color: #000000"
          >Send Message</a
        >
      </div>
      <!-- <div class="col-4"></div> -->
    </div>
  </div>
  {% endfor %}

  <!-- <div class="row">
    <div class="col">
      <a href="https://www.transitionbikes.com/Home.cfm" target="_blank"
        ><img
          src="/static/pictures/pics/tranny.png"
          class="img-fluid"
          style="margin-top: 5px"
      /></a>
    </div>

    <div class="col">
      <a href="https://www.transitionbikes.com/Home.cfm" target="_blank">
        <img src="/static/pictures/pics/norco.png" class="img-fluid" />
      </a>
    </div>
  </div>
</div> -->

  <!-- <div class="row align-items-center justify-content-between">
  <div class="col-md p-5">
    <img src="/static/pictures/pics/tranny.png" class="img-fluid" />
  </div>
  <div class="col-md p-5">
    <h2>Transition Bikes</h2>
    <p class="lead">
      We are proud to be one of the largest Transition Bikes dealers in Canada!
      Transition is a local company from just south of the border, in
      Bellingham, WA. They make high end mountain bikes for all types of riding
      from XC to DH. We are always well stocked in everything Transition offers.
      Their bikes have been proven by multiple editorial awards in recent years
      and always guarantee a party in the woods!
    </p>
    <a
      href="https://www.transitionbikes.com/Home.cfm"
      target="_blank"
      class="btn1"
      >Visit Transition</a
    >
  </div>
</div> -->

  <!-- <section class="section2">
  <div class="container">
    <div class="row align-items-center justify-content-between">
      <div class="col-md p-5">
        <h2>Norco Bicycles</h2>
        <p class="lead">
          Norco is a local brand from Coquitlam, BC that have a broad range of
          bikes. We have Norco mountain bikes for all riders, from beginners
          looking to do some trails and city riding, to experts wanting the
          fastest and most advanced bike you can buy.
        </p>
        <a href="https://www.norco.com/" target="_blank" class="btn1"
          >Visit Norco</a
        >
      </div>
      <div class="col-md p-5">
        <img src="/static/pictures/pics/norco.png" class="img-fluid" />
      </div>
    </div>
  </div>
</section> -->

  {% endblock %}
</div>

website/templates/bikesPB.html
{% extends "base.html" %} {% block title %}Changed{% endblock %} {% block
content %}

<div class="bikes">
  <div class="bikeinfo">
    Below is a list of some in-stock bikes we have. We do a fairly good job of
    updating, but it is not always accurate of our stock. We have many more
    bikes in stock than just these. If you are interested in any of these bikes,
    or other options you don't see here, contact us.
  </div>
  {% for r in result %}
  <div class="bike-line"></div>
  <div class="bike">
    <div class="row align-items-center">
      <div class="col-6">
        <a href="{{ r.src }}" target="_blank">
          <img
            src="{{ r.src }}"
            alt=""
            class="img-fluid"
            style="border-radius: 5%"
          />
        </a>
      </div>
      <div class="col-6">
        <a href="{{ r.bike_page }}" target="_blank" style="color: #000000"
          ><div class="title">{{ r.desc }}</div></a
        >
        <div class="title">{{ r.price }}</div>
        {{ r.size }} <br />
        {{ r.wheelsize }}<br />
        {{ r.mat }} <br />
        {{ r.front_travel }} <br />
        {{ r.rear_travel }} <br />
        <a
          href="{{url_for('views.contact', info='0', _anchor='bottom')}}"
          target="_blank"
          style="color: #000000"
          >Send Message</a
        >
      </div>
      <!-- <div class="col-4"></div> -->
    </div>
  </div>

  {% endfor %}
</div>
{% endblock %}

website/templates/contact.html
{% extends "base.html" %} {% block title %}Changed{% endblock %} {% block
content %}

<section class="section1">
  <div class="container">
    <div class="row align-items-center justify-content-between">
      <div class="col-md order-last">
        <!-- <div class="box"> -->
        <div class="map">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2600.392617088296!2d-123.07467488441526!3d49.325785175636774!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x548670479ba62361%3A0x3bb6e7001e8fc223!2sNorth%20Shore%20Bike%20Shop!5e0!3m2!1sen!2sca!4v1662267263686!5m2!1sen!2sca"
            width="100%"
            height="100%"
            style="border: 0"
            allowfullscreen=""
            loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"
          ></iframe>
          <!-- </div> -->
        </div>
      </div>
      <div class="col-md p-5 order-first">
        <div class="box5">
          <h1>North Shore Bike Shop</h1>

          <h4>North Vancouver</h4>
        </div>
        <div class="box">
          <h4 class="text-center">
            1831 Lonsdale Avenue <br />
            North Vancouver, BC <br />
            V7M 2J8
          </h4>
        </div>

        <div class="box">
          <table>
            <tr>
              <th></th>
              <th>Open</th>
              <th>Close</th>
            </tr>
            <tr>
              <th>Monday</th>
              <th>11:00 AM</th>
              <th>7:00 PM</th>
            </tr>
            <tr>
              <th>Tuesday</th>
              <th>11:00 AM</th>
              <th>7:00 PM</th>
            </tr>
            <tr>
              <th>Wednesday</th>
              <th>11:00 AM</th>
              <th>7:00 PM</th>
            </tr>
            <tr>
              <th>Thursday</th>
              <th>11:00 AM</th>
              <th>7:00 PM</th>
            </tr>
            <tr>
              <th>Friday</th>
              <th>11:00 AM</th>
              <th>7:00 PM</th>
            </tr>
            <tr>
              <th>Saturday</th>
              <th>10:00 AM</th>
              <th>6:00 PM</th>
            </tr>
            <tr>
              <th>Sunday</th>
              <th>11:00 AM</th>
              <th>4:00 PM</th>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- <section class="section2">
      <div class="container">
        <div>
          <h1>
            Come see us in person, call, or email. We are always happy to help.
          </h1>
          <br />
          <h2>
            Phone Number: (604) 929-6727
            <a
              href="https://www.transitionbikes.com/Home.cfm"
              target="_blank"
              class="btn1"
              >Call Us</a
            >
          </h2>

          <h2>
            Cell Number (text also availiable): (604) 929-6727
            <a
              href="https://www.transitionbikes.com/Home.cfm"
              target="_blank"
              class="btn1"
              >Call Us</a
            >
          </h2>
          <h2>
            Email: northshorebikeshop@gmail.com
            <a
              href="https://www.transitionbikes.com/Home.cfm"
              target="_blank"
              class="btn1"
              >Email Us</a
            >
          </h2>
        </div>
      </div>
    </section> -->

<a id="contact"></a>
<!-- <div class="container">
  <div class="row align-items-center justify-content-between">
    <div class="col-md p-5 text-center">
      <i class="fa-solid fa-phone fa-7x"></i>
      <h3>
        <br />
        Phone
      </h3>
      <p class="lead">(604) 929-6727 (call) <br />(604) 929-6727 (text)</p>
      <a href="tel:16049296727" target="_blank" class="btn1">Call</a>
    </div>
    <div class="col-md p-5 text-center">
      <i class="fa-solid fa-envelope fa-7x"></i>
      <h3><br />Email</h3>
      <p class="lead">northshorebikeshop@gmail.com</p>
      <a href="mailto:northshorebikeshop@gmail.com" target="_blank" class="btn1"
        >Email</a
      >
    </div>
  </div>
</div> -->
<a class="anchor" id="bottom"></a>
<div
  style="
    font-family: open-sans, sans-serif;
    font-size: 40px;
    margin-left: 5%;
    margin-top: 2%;
    font-weight: 600;
  "
>
  Contact Us
</div>
<div
  style="
    font-family: open-sans, sans-serif;
    font-size: 20px;
    margin-left: 5%;
    margin-right: 5%;
    margin-bottom: 2%;
  "
>
  If you have any questions, inquiries, or just want to chat about bikes, don't
  hesitate to contact us! We try to reply to emails within the business day.
  Fill out the form below and we will reply via email or you can just use
  <a href="mailto:northshorebikeshop@gmail.com" target="_blank"
    >northshorebikeshop@gmail.com</a
  >
  to email us.
</div>
<div
  style="font-family: open-sans, sans-serif; font-size: 20px; margin-left: 5%"
>
  You can also call us at
  <a href="tel:16049296727" target="_blank">(604) 929-6727</a> or call and text
  us at <a href="tel:16049286727" target="_blank">(604) 928-6727</a>.
</div>
<form action="/form" method="POST" style="margin-top: 2%">
  <div
    style="font-family: open-sans, sans-serif; font-size: 30px; margin-left: 5%"
  >
    Email Form
  </div>
  <div
    class="form-group"
    style="margin-left: 5%; margin-top: 2%; margin-right: 5%"
  >
    <label for="name">Your Email</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter your email (we will contact you here)"
    />
    <label for="name" style="margin-top: 1%">Your Name</label>
    <input
      type="name"
      class="form-control"
      id="name"
      name="name"
      placeholder="Enter your name"
    />
    <label for="name" style="margin-top: 1%">Subject</label>
    <input
      type="subject"
      class="form-control"
      id="subject"
      name="subject"
      placeholder="Enter email subject"
    />
    <label for="name" style="margin-top: 1%">Message</label>
    <!-- <input
      type="message"
      class="form-control"
      id="message"
      name="message"
      placeholder="Enter your message"
    /> -->
    <textarea
      type="message"
      class="form-control"
      id="message"
      name="message"
      placeholder="Enter your message"
      rows="5"
    ></textarea>
  </div>
  <br />
  <button
    type="submit"
    style="margin-left: 5%; margin-bottom: 20px"
    class="btn-card"
  >
    Submit
  </button>
</form>
{% endblock %}

website/templates/index.html
{% extends "base.html" %} {% block title %}Changed{% endblock %} {% block
content %}
<!-- 
<div class="textonimage">
  <img src="/static/pictures/pics/SIK09398.jpg" alt="" />
  <darkness class="darkness"></darkness>
  <div class="logoonimage">
    <img src="/static/pictures/pics/logo_northshorebikeshop.png" alt="" />
    <caption1 class="caption1">
      Your Local Mountain Bike Experts <br />
    </caption1>
    <caption2 class="caption2">
      North Shore Bike Shop is proudly serving the mountain bike community since
      2007. <br />
      <br />
      We are a group of passionate mountain bikers who are also keenly focused
      on delivering excellent customer service.
    </caption2>
  </div>
</div> -->

<div class="parent">
  <img src="/static/pictures/pics/lars.jpeg" class="image1" />
  <div class="child">
    <img src="/static/pictures/pics/logoforimage.png" class="image2" />
    <div class="imagetext">Your local mountain bike experts since 2007</div>
  </div>
</div>

<section class="section2">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 text-center">
      <div>
        <img
          src="/static/pictures/pics/store.png"
          alt=""
          height="200"
          width="350"
          style="border-radius: 5%"
        />
      </div>
      <div>
        <a href="{{url_for('views.contact', info='0')}}" class="btn-card"
          >Visit or Contact Us</a
        >
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 text-center">
      <div>
        <img
          src="/static/pictures/nsbs photos/20221014_195557.jpg"
          alt=""
          height="200"
          width="350"
          style="border-radius: 5%"
        />
      </div>
      <div>
        <a href="{{url_for('views.bikes')}}" class="btn-card">Shop at NSBS</a>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 text-center">
      <div>
        <img
          src="/static/pictures/nsbs photos/IMG_1087.jpg"
          alt=""
          height="200"
          width="350"
          style="border-radius: 5%"
        />
      </div>
      <div>
        <a href="{{url_for('views.service')}}" class="btn-card">NSBS Service</a>
      </div>
    </div>
  </div>
</section>
<!-- 
<section class="section1">
  <div class="row">
    <div class="col">asdfasdf</div>
    <div class="col">
      <img
        src="/static/pictures/nsbs photos/20221014_194941.jpg"
        class="img-fluid"
        alt=""
      />
    </div>
  </div>
</section> -->
<!-- 
<section class="section1">
  <div class="row align-items-center">
    <div class="col">
      <div class="text-pictures">
        <img src="/static/pictures/nsbs photos/20221014_194941.jpg" alt="" />
      </div>
    </div>
    <div class="col"><div class="text-text">asdfasd</div></div>
  </div>
</section> -->

<div
  class="row gx-0 align-items-center"
  style="background-color: var(--zigzag-bg-color)"
>
  <div class="col-lg">
    <img
      src="/static/pictures/nsbs photos/20221014_194941.jpg"
      width="100%"
      alt=""
    />
  </div>
  <div class="col-lg" style="background-color: var(--zigzag-bg-color)">
    <div class="zigzag">Shop Bikes</div>
    <div class="zigzag-text">
      NSBS is well-stocked with youth bikes, dirt jumpers, trail, enduro and
      downhill bikes. Whether you are looking for an entry-level hardtail or the
      best bike money can buy, you will have options at NSBS.
    </div>
    <a href="{{url_for('views.bikes')}}" class="zigzag-button">More Info</a>
  </div>
</div>

<div
  class="row gx-0 align-items-center flex-column-reverse flex-lg-row"
  style="background-color: var(--zigzag-bg-color)"
>
  <div class="col-lg" style="background-color: var(--zigzag-bg-color)">
    <div class="zigzag">Shop Parts and Gear</div>
    <div class="zigzag-text">
      At North Shore Bike Shop you will only find proven brands. Whether you
      need a replacement to get your bike going, or you want to upgrade to the
      latest and greatest, our shop is always ready to meet your biking needs.
    </div>
    <a href="{{url_for('views.shop')}}" class="zigzag-button">More Info</a>
  </div>
  <div class="col-lg">
    <img src="/static/pictures/nsbs photos/im2.jpg" width="100%" alt="" />
  </div>
</div>

<div
  class="row gx-0 align-items-center"
  style="background-color: var(--zigzag-bg-color)"
>
  <div class="col-lg">
    <img src="/static/pictures/nsbs photos/IMG_1090.jpg" width="100%" alt="" />
  </div>
  <div
    class="col-lg align-items-center"
    style="background-color: var(--zigzag-bg-color)"
  >
    <div class="zigzag">Service</div>
    <div class="zigzag-text">
      Our service department is tidy, fast, and staffed with competent mechanics
      who are eager to see you back on your bike. Our turn-around time is
      unmatched anywhere else in town. We fix everything bicycle related.
    </div>
    <a href="{{url_for('views.service')}}" class="zigzag-button">More Info</a>
  </div>
</div>

{% endblock %}